"""add_user_id_to_tags

Revision ID: 0312cb6ab39f
Revises: 7e39b03d5290
Create Date: 2025-11-08 22:33:19.406736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0312cb6ab39f'
down_revision = '7e39b03d5290'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Constraints already exist in database, skip creation

    # Add user_id column as nullable first
    op.add_column('tags', sa.Column('user_id', sa.UUID(), nullable=True))

    # Migrate existing tags: assign to users based on their log associations
    # This SQL finds the first user who used each tag and assigns ownership
    op.execute("""
        UPDATE tags
        SET user_id = (
            SELECT logs.user_id
            FROM tag_log
            JOIN logs ON tag_log.log_id = logs.id
            WHERE tag_log.tag_id = tags.id
            LIMIT 1
        )
        WHERE user_id IS NULL
    """)

    # Delete orphaned tags (tags with no associated logs)
    op.execute("""
        DELETE FROM tags
        WHERE user_id IS NULL
    """)

    # Now make user_id NOT NULL
    op.alter_column('tags', 'user_id', nullable=False)

    op.drop_index('ix_tags_name', table_name='tags')
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_unique_constraint('uq_user_tag_name', 'tags', ['user_id', 'name'])
    op.create_foreign_key(None, 'tags', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint('uq_user_tag_name', 'tags', type_='unique')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.create_index('ix_tags_name', 'tags', ['name'], unique=False)
    op.drop_column('tags', 'user_id')
    op.drop_constraint('uq_tag_log', 'tag_log', type_='unique')
    op.drop_constraint('uq_theme_log', 'log_theme', type_='unique')
    # ### end Alembic commands ### 