"""Add updated_at timestamp to themes table

Revision ID: 7e39b03d5290
Revises: 35b68fd1ada1
Create Date: 2025-08-05 00:46:39.488402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e39b03d5290'
down_revision = '35b68fd1ada1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('themes', 'updated_at')
    # ### end Alembic commands ### 