from typing import List, Optional, Any
from enum import Enum

class _SchemeType:
    CKKS: int

SCHEME_TYPE: _SchemeType

class Context:
    def serialize(self, save_secret_key: bool = True) -> bytes: ...
    def is_private(self) -> bool: ...
    def generate_galois_keys(self) -> None: ...
    def generate_relin_keys(self) -> None: ...
    @property
    def global_scale(self) -> float: ...
    @global_scale.setter
    def global_scale(self, value: float) -> None: ...

class CKKSVector:
    def serialize(self) -> bytes: ...
    def decrypt(self) -> List[float]: ...
    def __add__(self, other: CKKSVector) -> CKKSVector: ...
    def __mul__(self, scalar: float) -> CKKSVector: ...

def context(
    scheme: int,
    poly_modulus_degree: int,
    coeff_mod_bit_sizes: List[int],
) -> Context: ...

def context_from(data: bytes) -> Context: ...

def ckks_vector(context: Context, data: List[float]) -> CKKSVector: ...

def ckks_vector_from(context: Context, data: bytes) -> CKKSVector: ...
